### ISSUE TITLE
Code testing

### ISSUE THREAD

**Issue by bherr2** [hubmapconsortium/hubmap-ontology#10]
Provide unit tests for all code. Use unittest, doctest, or similar to test the code. We are looking for 80% or greater code coverage. We use SONAR for our code coverage and linting. If you don't have a strong preference use that ([Sonar Python](https://www.sonarsource.com/products/codeanalyzers/sonarpython.html)) and integrate into the continuous integration pipeline. @gurjaspalbedi from our team can help with the SONAR integration.

**Comment by SamuelFriedman** [comment]
We need a dummy/simple input ontology and a separate dummy/simple output ontology for testing purposes. Maybe find a smaller ontology in OBO Foundry?

**Comment by jpsluka** [comment]
need 4 or more classes, four or more sublets
need subclass, partOf, and a few other (random) predicates just to make sure predicates and triples are removed.

**Comment by SamuelFriedman** [comment]
@jpsluka recommended the KTAO as a sample ontology. However, I then also need a list of terms to include for subset/slim selection.

**Comment by SamuelFriedman** [comment]
We have a set of terms and it has been included. The test code runs and outputs test files.

**Comment by SamuelFriedman** [comment]
To run the test code, run
`python3 -W ignore test/test_ktao_slim.py`
