### ISSUE TITLE
Workflow documentation

### ISSUE THREAD

**Issue by bherr2** [hubmapconsortium/hubmap-ontology#11]
Document the workflow from a high level. Documentation should be committed to the repository as Markdown and converted to HTML for publication to `gh-pages` as part of the continuous integration. [pandoc](https://pandoc.org/) would be a good tool for conversion.

**Comment by SamuelFriedman** [comment]
Transform Google Doc documentation to Markdown

**Comment by SamuelFriedman** [comment]
We are making the Google Doc the master document. We will save snapshots of the Google Doc as Microsoft Word Docx and a PDF for release in a snapshot.
