### ISSUE TITLE
Add full description of predicates used

### ISSUE THREAD

**Issue by SamuelFriedman** [hubmapconsortium/hubmap-ontology#15]
e.g.,  names BFO_0000050-->part_of

This could be as simple as Ontospy building everything.

**Comment by SamuelFriedman** [comment]
BFO_00000050 now displays in Protege as part_of. Many other properties are also added, namely 361 from UBERON. This seems to have fixed the problem.

**Comment by SamuelFriedman** [comment]
In future, we would like to import RO, BFO, IAO terms directly from those ontologies and not through the extended version of UBERON.

**Comment by jpsluka** [comment]
Did a quick test with Sam's ontology pulled 6 May 2019, added RO as an import;
Immediately after the line;
        xmlns:insect-anatomy="http://purl.obolibrary.org/obo/uberon/insect-anatomy#">

Added;
    <owl:Ontology>
        <owl:imports rdf:resource="http://purl.obolibrary.org/obo/ro/releases/2019-02-02/ro.owl"/>
    </owl:Ontology>

This version of Sam's ontology now includes all the comments, notes etc. for terms in RO. For example Part Of now has;
   definition: a core relation that holds between a part and its whole.
which was missing before.

I think for the time being we just leave things as is. We can revisit the need to import other ontologies later.

BTW: we have an alias for "insect-anatomy" and it is used about 12 times. LOL
