### ISSUE TITLE
Minor file cleanup

### ISSUE THREAD

**Issue by bherr2** [hubmapconsortium/hubmap-ontology#20]
* [ ] Please rename all jsonld files to end in .jsonld.
* [ ] I saw there is another partonomy.jsonld.owl one level up in the partonomy folder which I believe should be deleted. If not, put into reifications and made distinct from the other .jsonld. I believe this is the full partonomy with all the cruft and different from the stripped down partonomy we will use in the CCF-UI. Maybe the stripped down version should be partonomy.simplified.jsonld?
* [ ] At the very top level there is an ext.owl which I thought you moved into src/input_data.
* [ ] Should ccf_input_terms.csv and filter_terms.xlsx go into input_data as well?

**Comment by SamuelFriedman** [comment]
Everything makes sense except the filter_terms.xlsx move because that was part of a broader effort to develop ontological terms that were for the metadata or related to antigens. I honestly think the file should just be removed.
