### ISSUE TITLE
Link to Partonomy visualization

### ISSUE THREAD

**Issue by bherr2** [hubmapconsortium/hubmap-ontology#21]
I ended up creating a visualization of the partonomy to make sure it'd work using Vega. I'm not sure where it'd be best to keep this, but may be worth having a link somewhere to it (or even adding the vega visualization spec to the repo).

You can see the visualization [here](https://vega.github.io/editor/#/gist/vega/bherr2/542482aea690cea2a299f5153aa212eb/90ac7717b3500f84b163ff16c8c2bb83f9d90ce1/hubmap-partonomy.vg.json/view)

**Comment by SamuelFriedman** [comment]
Put this link in the main README file.

**Comment by SamuelFriedman** [comment]
Done
