### ISSUE TITLE
Create partOf subclass term for visualization

### ISSUE THREAD

**Issue by SamuelFriedman** [hubmapconsortium/hubmap-ontology#6]
To create a more human friendly partonomy, add an additional partOf subclass and connect the partonomy nodes with it. Work closely with @jpsluka to get the right structure which will be used in the CCF UI.

**Comment by SamuelFriedman** [comment]
Write SPARQL query to return all partOf triples where partOf is the predicate.

**Comment by SamuelFriedman** [comment]
@jpsluka and @SamuelFriedman need to talk more about what exactly we want.

We wanted multiple part_of edges replaced by a single part_of edge where each connecting node along the way only was one incoming edge and one outgoing edge. Thus, we want to skip over such nodes.

**Comment by SamuelFriedman** [comment]
@jpsluka Any ideas about what you want to do for such an element? I think that creating a subclass of part_of is not necessarily the right path because it is such a high level element. I'm more inclined simply to remove those nodes that only have one incoming and one outgoing edge and replace those edges with a single edge between the child and parent node. The child node *is* a part of its grandparent. We need to get this done by April 30 for the 0.3.0 release.

**Comment by jpsluka** [comment]
we have to be careful with removing partOf's that came from UBERON (or the ontologies that UBERON was created from). The correct solution would be to create a new relationship specific for the HuBMAP UI. OWL allows sub-relationships, so we can define, e.g., partOf_HuBMAP as a sub-relationship of partOf. Initially we just duplicate the existing partOf's as new partOf_HuBMAP relationships. We then edit these new partOf's to represent how we want to navigate in the UI.

**Comment by SamuelFriedman** [comment]
We will duplicate the partOf relationships that we want to include and make the terms partOf_HUBMAP.
